### ISSUE TITLE
Problem Set 8

### ISSUE THREAD

**Issue by calebki94** [AmherstCollege/STAT370-S16-GroupIV#7]
Hi Nick,

Are we supposed to just change values for beta1 and then show the different tables for each different value? We are looking for how changing beta1 effects the bias and mse. Is that correct?

**Comment by nicholasjhorton** [comment]
Tables or graphs (plus interpretation).  Please see my note to the class as a whole for more details.

Nick

> On Apr 24, 2016, at 7:57 PM, calebki94 <notifications@github.com> wrote:
> 
> Hi Nick,
> 
> Are we supposed to just change values for beta1 and then show the different tables for each different value? We are looking for how changing beta1 effects the bias and mse. Is that correct?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> 

Nicholas Horton 
Professor of Statistics
Department of Mathematics and Statistics, Amherst College
Box 2239, 31 Quadrangle Dr
Amherst, MA 01002-5000
https://www.amherst.edu/people/facstaff/nhorton
