### ISSUE TITLE
TAS Papers

### ISSUE THREAD

**Issue by calebki94** [AmherstCollege/STAT370-S16-GroupIV#9]
Our top two choices are:

6. The Decline and Fall of Type II Error Rates
18. Hidden Dangers of Specifying Noninformative Priors

**Comment by nicholasjhorton** [comment]
The Decline and Fall is all yours.

Nick

> On Apr 25, 2016, at 4:00 PM, calebki94 <notifications@github.com> wrote:
> 
> Our top two choices are:
> 
> 	• The Decline and Fall of Type II Error Rates
> 	• Hidden Dangers of Specifying Noninformative Priors
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> 

Nicholas Horton 
Professor of Statistics
Department of Mathematics and Statistics, Amherst College
Box 2239, 31 Quadrangle Dr
Amherst, MA 01002-5000
https://www.amherst.edu/people/facstaff/nhorton
